### ISSUE TITLE
Python version requirement problem

### ISSUE THREAD

**Issue by jwbos** [mupq/pqm4#111]
The current ReadMe file states “_The benchmarking scripts used in pqm4 require Python >= 3.6._”
However,  the mupq.py file has the line
`subprocess.check_output(args, *, stdin=None, stderr=None, shell=False, cwd=None, encoding=None, errors=None, universal_newlines=None, timeout=None, text=None)`
The “text” option was only added in Python 3.7 (“_New in version 3.7: text was added as a more readable alias for universal_newlines._”). 
A solution is either requiring Python >= 3.7 or using the universal_newlines option instead.

**Comment by Ko-** [comment]
Hi! Thanks for catching that and reporting it. We have to admit that we're all on more recent versions ourselves. We'll probably replace it by `universal_newlines` as soon as possible.
