### ISSUE TITLE
Possible minor bug in verify function of NewHopeKEM

### ISSUE THREAD

**Issue by PRASANNA-RAVI** [mupq/pqm4#132]
The verify function in verify.c in the NewHope implementation compares two arrays for equality in constant time and should return (r = 0) if the byte arrays are equal and return (r = 1) otherwise. On executing a decapsulation with a faulty ciphertext, it should return r = 1, however I think it is returning r = 0xFF.  Due to this, the cmov function subsequently executed during decapsulation in kem.c does not perform correct swapping between the bytes arrays x and r. I think it can be fixed by replacing line 25 in verify.c (i.e) 

r = (-(int64_t)r) >> 63

with 

r = (-r) >> 63;    or      r = ((uint64_t)(-(int64_t)r)) >> 63;

I do believe that the most recent implementation of NewHope does not use this verify function though the verify function is defined in verify.c, but this function has been utilized in previous implementations of NewHope in the pqm4 library.

**Comment by mkannwischer** [comment]
Thanks @PRASANNA-RAVI for reporting this. 
I can confirm this bug, but it's returning `0` or `-1` (which when cast to `unsigned int` turns into `0xff`.) 
Indeed, the function got in-lined in the current implementation in pqm4, so we can simply remove it here. 

However, I checked the reference implementation of NewHope and there this problem does not exist! 
They simply do 
`r = (-r) >> 63;` which seems to correctly yield `1` or `0`, but if I recall correctly it gives a compiler warning on Windows.
Therefore, when I integrated this into PQClean, I added a cast that resolved the warning, but apparently also broke the code: https://github.com/PQClean/PQClean/pull/160 
And in the PQClean code this actually is used and, thus, is a problem. 
I will fix it there asap.
