### ISSUE TITLE
Integrate Saber M4 implementation

### ISSUE THREAD

**Issue by Ko-** [mupq/pqm4#140]
There's a new improved Saber implementation of https://eprint.iacr.org/2020/268.pdf. The source code is on [GitHub](https://github.com/KULeuven-COSIC/SABER) and I started integrating that in the [saber-tches2020](https://github.com/mupq/pqm4/tree/saber-tches2020) branch. However, I ran into some [issues](https://github.com/KULeuven-COSIC/SABER/issues/1).

**Comment by mkannwischer** [comment]
That implementation is outdated now. I've merged the faster one in #167. 
There is an even faster one to come that needs even less RAM: https://github.com/ntt-polymul/ntt-polymul/issues/2.
