### ISSUE TITLE
Add new candidate Round5 ( = Round2 + Hila5 )

### ISSUE THREAD

**Issue by mjosaarinen** [mupq/pqm4#15]
Round5 should meet your inclusion requirements -- having a version at Category 3 and being in the NIST competition (NIST has approved the merger of Round2 and Hila5 teams).

Code at https://github.com/round5/r5nd_tiny should be easy enough to incorporate to your testing framework. I actually used your implementations in benchmarking (thanks!) so APIs are equivalent. I simply had a different vendor board (with different flashing and serial comms mechanisms) so can't integrate it directly.

Please see the paper "Shorter Messages and Faster Post-Quantum Encryption with Round5 on Cortex M" at https://round5.org/doc/r5m4text.pdf for more information. It should pop up in IACR ePrint shortly.

Cheers,
- markku

**Comment by cryptojedi** [comment]
Would be great to have Round-5 without any patents. While there are still patent claims by the authors, we'd rather not merge into pqm4.
