### ISSUE TITLE
Fix timing leakage in FrodoKEM (and others?)

### ISSUE THREAD

**Issue by Ko-** [mupq/pqm4#161]
In [this CRYPTO paper](https://eprint.iacr.org/2020/743) a timing attack on some implementations of the FO transform was identified. This affects decapsulation in FrodoKEM, which was fixed in microsoft/PQCrypto-LWEKE@155c24c and PQClean/PQClean@ae1530d. It doesn't change the test vectors or anything, but it's probably best to update pqm4 as well. The `m4` implementations are also affected. Although I expect the impact on benchmarks to be negligible, we should probably rerun the benchmarks.

It's not clear to me at this point which other implementations that do claim constant-time-ness require changes.

**Comment by henrydcase** [comment]
if you still consider sike then it has similar issue (but not exactly the same)
https://github.com/mupq/pqm4/blob/56417d9f69737c033715dab4957436bdfef91589/crypto_kem/sikep434/m4/sike.inc#L87
