### ISSUE TITLE
Stack usage results not useful for some schemes 

### ISSUE THREAD

**Issue by mkannwischer** [mupq/pqm4#18]
Schemes like Kindi use `malloc`/`calloc` extensively. 
While this still works on the M4, the stack usage benchmarks do no longer represent the entire memory consumption of the implementation. 
The cleanest solution would be to refactor those implementations not to use `malloc` etc.
Any other suggestions?

**Comment by cryptojedi** [comment]
"Matthias J. Kannwischer" <notifications@github.com> wrote:
> Schemes like Kindi use `malloc`/`calloc` extensively. 
> While this still works on the M4, the stack usage benchmarks do no longer represent the entire memory consumption of the implementation. 
> The cleanest solution would be to refactor those implementations not to use `malloc` etc.

Indeed, that would be the best solution.

**Comment by cryptojedi** [comment]
Ko- <notifications@github.com> wrote:
> It never represented the entire memory consumption. In `pqm4` we
> currently don't measure the code size or
> uninitialized/zero-initialized global/static local variables of the
> `.bss` or all the other stuff that ends up taking space in flash
> memory. `st-flash` also loads a flash loader in RAM that we don't (and
> shouldn't) take into account. Instead of getting an idea of the full
> memory requirements, we just take one metric that we assume is
> probably going to be the most restrictive and compare the schemes
> based on that.
 
> In any case, I think it would be nicer to avoid using `malloc` et al.
> on microcontrollers. 

For crypto code, such as all the software in pqm4, yes. Let's remove all
mallocs.
 
> So... I don't know. I think I would vote for just forbidding
> `malloc`/`calloc`/`realloc` and replacing them by statically allocated
> memory chunks sized for the worst case for those parameters, also in
> `ref/` implementations. At least as long as it is known at compile
> time what size is large enough. A quick `grep` shows that all calls to
> `malloc`/`calloc`/`realloc` are actually used with a constant size,
> except for the `malloc` in
> `crypto_kem/kindi256342/ref/gen_randomness.c:kindi_crypto_stream_h`,
> that is either called with `KINDI_KEM_S1SIZE+1` or with
> `KINDI_KEM_CIPHERBYTES+KINDI_KEM_S1SIZE+1`. We could either always
> allocate the latter value or be kind and split the function in two
> versions.
> 
> What do you guys think?

In this case, split the function in two versions.
