### ISSUE TITLE
A bug in decasuplation function of NTRU Prime implementation

### ISSUE THREAD

**Issue by arokiti** [mupq/pqm4#195]
Hi. I found a bug in the decapsulation function of the NTRU Prime implementation. Specifically, the "Ciphertexts_diff_mask" function in kem.c of sntrup761 returns a mask value as follows:
```
1112:   return ((-1)-((differentbits-1)>>31));
```
However, this function always returns 0  because the variable "differentbits" is always 0. Probably, "differentbits2" is correct, not "differentbits". Therefore, I think it can be fixed by replacing
```
1112:   return ((-1)-((differentbits-1)>>31));
```
with
```
1112:   return ((-1)-((differentbits2-1)>>31));
```

**Comment by mkannwischer** [comment]
Sorry for the super long delay. 
Thanks for reporting this obvious bug. I agree with your fix and it will shortly be merged.
