### ISSUE TITLE
dilithium2/m4 is not clear on licensing

### ISSUE THREAD

**Issue by hyandell** [mupq/pqm4#198]
Looking at the licensing in the repository, the crypto_sign/dilithium2/m4/ntt.s file has a GPL-3.0 source header, but there isn't a GPL-3.0 LICENSE (or COPYING) file higher in the directory structure (per the README's statement that other licensing is identified in LICENSE files).

**Comment by mkannwischer** [comment]
Thanks for reporting this. I'm bothered by this GPL license for a while already.
I've checked with Markus Krausz and he agreed to also put it under CC0 as the rest of the code. 
I'll update it shortly.
