### ISSUE TITLE
Makefile does not generate "bin" folder

### ISSUE THREAD

**Issue by rprimas** [mupq/pqm4#205]
If I execute "make -j4 PLATFORM=stm32f4discovery" using the most recent code version then only an "elf" directory is created at top-level but not a "bin" directory. This is inconsistent with the readme which uses bin files for flashing, e.g.: "st-flash write bin/crypto_kem_kyber768_m4_test.bin 0x8000000".

It is still possible to generate bin files manually like so: "make bin/crypto_kem_kyber768_m4_test.bin".

**Comment by rpls** [comment]
There should also be the `tests-bin` target. I guess we should add this to the default `make` target. I guess this shows that we mostly tested with the python script, which requests the `bin`/`hex` files.
