### ISSUE TITLE
Windows: problematic file names "aux.S"

### ISSUE THREAD

**Issue by ppessl** [mupq/pqm4#216]
The current Saber implementations use files named "aux.S". "aux" cannot be used as a file name in Windows, thus these files cause all sorts of problems, such as failing git clone / pull.

I suggest to rename these files.

**Comment by mkannwischer** [comment]
Windows never ceases to impress and annoy me. 
Thank you @ppessl for reporting that issue. Should be fixed now. 
Let me know if there are any other problems.
