### ISSUE TITLE
Need help in identifying the board 

### ISSUE THREAD

**Issue by samyuktha123sets** [mupq/pqm4#225]
Hi Team,
 
In order to execute the PQ implementations, is it necessary that I use the `STM32F407G-DISC1` board. As the board is not available on many websites, would it be okay if I run the PQ implementations on `STM32F407VET6 Arm Cortex-M4 core with DSP and FPU` for benchmarking purposes?  It would be much helpful if you could share why `STM32F407G-DISC1` is most preferred.

**Comment by mkannwischer** [comment]
As long as your hardware is properly supported by libopencm3, you can get pqm4 to work with little effort. 
Most STM32 boards will be fine, you will only need to adapt the serial communication. 
Have a look at https://github.com/mupq/pqm4/blob/master/common/hal-opencm3.c. Adding another board should be easy. 
It will likely be exactly the same as the `DISCOVERY_BOARD`. 

https://github.com/mupq/pqm4/blob/master/mk/stm32f4discovery.mk should be easy to adapt for the STM32F407VET6. If I see correctly the only difference is that it only has 512 kB of flash?

Feel free to open a pull request once you got it to work. 

You can also drop me an e-mail. I might be able to help you out with a discovery board if you only need one.
