### ISSUE TITLE
update Saber code from upstream

### ISSUE THREAD

**Issue by vincentvbh** [mupq/pqm4#232]
It occurs to me that there might be the same issue for Saber as in https://github.com/mupq/pqm4/issues/226 even though we are using 32-bit iNTT.
I perform the range analysis again based on several worst-case scenarios and find that for firesaber, there might be an issue.
Therefore, I revised the 32-bit base multiplication since originally, we accumulate several base multiplications.
If we feed the worst-case result to the iNTT, then there might be a problem at layer 4 (0, 1, ..., 5).
After some adjustments in the base multiplication, the worst-case result should give a very close bound to 2^31 in absolute value, therefore, I decided to restore the Montgomery multiplication by 1 at layers 4 and 5.
This should solve the potential range issues.

The overall decrease of performance in the upstream is <1% for all parameters. So I don't think this will change any claims made by  https://github.com/multi-moduli-ntt-saber/multi-moduli-ntt-saber.

**Comment by mkannwischer** [comment]
Saber is no longer a candidate in the NIST competition and will be removed in #238. 
Closing this issue.
