### ISSUE TITLE
Issues calling C function from assembly code in Kyber matacc implementation

### ISSUE THREAD

**Issue by marco-palumbi** [mupq/pqm4#241]
I found a couple of issues related to the call of a C function from the assembly code:

- Register r12 is not saved and restored when calling **kyber_shake128_squeezeblocks()** in both kyber m4fspeed and m4fstack. According with the arm C calling convection, register r12 can be freely overwritten by the called C function.
- Floating point registers from s0 to s15 are used but not saved from the caller across the called C function. According with the arm C calling convection, registers from s0 to s15 can be freely used from a function (thus they must saved by the caller if needed) while registers from s16 to s31 must be preserved by the callee function that means that s0 to s16 may be clobbered by the called C funtion.

Although there are currently no problems with the called C functions, I recommend fixing the problem (I actually had issues with a different implementation of shake)

I suggest:

- save r12 across the C function call
- use the s16-s31 register and instruct the compiler to consider clobbered the used s registers before calling the matacc assembly code

I created PR #240 to fix the Issue

See:
[Procedure Call Standard for the ARM Architecture](https://web.eecs.umich.edu/~prabal/teaching/resources/eecs373/ARM-AAPCS-EABI-v2.08.pdf) par 5.1.1 and 5.1.2.1

**Comment by mkannwischer** [comment]
Fixed by #240. Thanks @marco-palumbi!
