### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by derstrand** [mupq/pqm4#246]

**Comment by derstrand** [comment]
Dear pqm4 community,

I have tried to build pqm4 library on an Ubuntu host. Followed all steps outlined, and tried to build for mps2-an386 platform. Build fails with the following errors. 

<img width="765" alt="build_error" src="https://user-images.githubusercontent.com/116235277/197287427-e0d34ab6-8756-413e-9329-bf69acd26954.png">

Best,
@derstrand

**Comment by mkannwischer** [comment]
Do you mind trying a newer compiler from https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads and/or let me know what compiler you are using

**Comment by derstrand** [comment]
Thank you, @mkannwischer. I will have a look at the those compilers. Currently, I have:
derstrand> gcc --version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0

**Comment by mkannwischer** [comment]
I am assuming this resolved the issue? 
Closing this.
