### ISSUE TITLE
Size of the Input for Benhmarks 

### ISSUE THREAD

**Issue by shafqatu** [mupq/pqm4#250]
Hi Y'all, 

So, I see good benchmarks.md file, but I don't see what was the input test vector and size of it, can someone please point me to the input test vectors and vector sizes used for all the tests?

BR
/Shafqat

**Comment by mkannwischer** [comment]
I am not sure if I understand what you mean by input test vector. 
Do you mean the length of the message that is being signed? We are signing 59-byte messages. You can see that here: https://github.com/mupq/mupq/blob/3b48fa5aff6f5921df5b3444450281daca6d21d1/crypto_sign/speed.c

**Comment by shafqatu** [comment]
Thank you I got my answer. I meant the length of message.
