### ISSUE TITLE
Add ALTEQ

### ISSUE THREAD

**Issue by mkannwischer** [mupq/pqm4#262]

**Comment by mkannwischer** [comment]
The current reference implementation available at https://pqcalteq.github.io/ALTEQ_code_2023.09.15.zip makes heavy use of dynamic memory allocations. 

There are also some doubts about the security of ALTEQ: https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/-LCPCJCyLlc/m/_ghV61NQBQAJ

**Comment by markuskrausz** [comment]
Requires too much RAM: The allocations + arrays in "crypto_sign" consume 1031600 bytes for Level 1 ShortSig-ALTEQ and 1911280 bytes for Level 1 Balanced-ALTEQ.
