### ISSUE TITLE
Add EagleSign

### ISSUE THREAD

**Issue by mkannwischer** [mupq/pqm4#267]

**Comment by markuskrausz** [comment]
Seems to be broken:
[https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/zas5PLiBe6A/m/tbRICkIbBgAJ](https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/zas5PLiBe6A/m/tbRICkIbBgAJ)

**Comment by mkannwischer** [comment]
Thx @markuskrausz
