### ISSUE TITLE
Add EHTv3 and EHTv4

### ISSUE THREAD

**Issue by mkannwischer** [mupq/pqm4#268]

**Comment by markuskrausz** [comment]
EHTv3 seems to be broken for level 1:
[https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/mFl_5Rq6-RU/m/po0lVaw9AgAJ](https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/mFl_5Rq6-RU/m/po0lVaw9AgAJ)

**Comment by mkannwischer** [comment]
Thx @markuskrausz

**Comment by markuskrausz** [comment]
The specification and implementation have been updated in response to the attacks:
[https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/rM7BkkoL2HE](https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/rM7BkkoL2HE)
