### ISSUE TITLE
Add eMLE-Sig 20

### ISSUE THREAD

**Issue by mkannwischer** [mupq/pqm4#269]

**Comment by markuskrausz** [comment]
Probably vulnerable/broken:
[https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/zas5PLiBe6A/m/aOnAlT6cAQAJ](https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/zas5PLiBe6A/m/aOnAlT6cAQAJ)
Mehdi and Lorenz demonstrated an attack on the original submission and on a first update intended to fix the issue.
Even after the second update, the attack seems to be feasible.

**Comment by mkannwischer** [comment]
Thx @markuskrausz
