### ISSUE TITLE
Add Enhanced pqsigRM

### ISSUE THREAD

**Issue by mkannwischer** [mupq/pqm4#270]

**Comment by markuskrausz** [comment]
The public key is too big for the pqm4 devices and the RAM usage is too high:
![grafik](https://github.com/mupq/pqm4/assets/57672970/64a3f4ef-bcd5-4b40-bfcc-e73f8c3e7c80)
![grafik](https://github.com/mupq/pqm4/assets/57672970/a3c05b44-ff04-4eda-a411-b3752be59d64)

**Comment by mkannwischer** [comment]
Thx @markuskrausz
