### ISSUE TITLE
Add MQOM

### ISSUE THREAD

**Issue by mkannwischer** [mupq/pqm4#283]

**Comment by markuskrausz** [comment]
Heavy use of dynamic memory allocation.

**Comment by mkannwischer** [comment]
Thanks @markuskrausz!

**Comment by mkannwischer** [comment]
Revisited this. It is going to be be *a lot* of work to refactor that since pointers are being return from the leaf functions to multiple layers. I'm hoping for the submission team to provide an implementation that is free of dynamic memory allocation at a later point.
