### ISSUE TITLE
Add Preon

### ISSUE THREAD

**Issue by mkannwischer** [mupq/pqm4#285]

**Comment by mkannwischer** [comment]
The Preon implementation available at https://csrc.nist.gov/csrc/media/Projects/pqc-dig-sig/documents/round-1/submission-pkg/Preon-submission-noKAT.zip is full of dynamic memory allocations and in it's current state not suitable for microcontrollers.

**Comment by markuskrausz** [comment]
![grafik](https://github.com/mupq/pqm4/assets/57672970/3f7128eb-02b4-4366-bc70-eef6e09636d3)
Additionally, the signature sizes are not suitable for most M4 devices.

**Comment by mkannwischer** [comment]
Additionally, it uses around 200 MB (Preon128A) of memory for signing right now.
