### ISSUE TITLE
Add TUOV

### ISSUE THREAD

**Issue by mkannwischer** [mupq/pqm4#295]

**Comment by markuskrausz** [comment]
Heavy use of dynamic memory allocation in the submitted code, the [git](https://github.com/tuovsig/tuov) with the latest code is empty.

**Comment by mkannwischer** [comment]
Thx @markuskrausz!

**Comment by rpls** [comment]
@mkannwischer @ilway25 since you already ported it, I'd say let's merge it anyway, so we at least have stack-benchmarks?

**Comment by rpls** [comment]
Merged in #327
