### ISSUE TITLE
Add VOX

### ISSUE THREAD

**Issue by mkannwischer** [mupq/pqm4#297]

**Comment by markuskrausz** [comment]
The reference implementation uses dynamic memory allocation:
![grafik](https://github.com/mupq/pqm4/assets/57672970/02a4a80a-db2b-44aa-b156-9753496f8569)
![grafik](https://github.com/mupq/pqm4/assets/57672970/0135606d-6661-46e8-bcae-7e03440ef9bc)

**Comment by mkannwischer** [comment]
Thx @markuskrausz. 
There are also some doubts about the security: https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/icHfTrzkfw4/m/Zj7GrnjMAQAJ
