### ISSUE TITLE
Add Wave

### ISSUE THREAD

**Issue by mkannwischer** [mupq/pqm4#298]

**Comment by mkannwischer** [comment]
Here are the key sizes from the spec: 
![image](https://github.com/mupq/pqm4/assets/3984960/bc1d7d3c-0e70-480f-a3ba-a877b2e8714b)

With public keys of > 3M this won't fit on any microcontroller.

**Comment by gbanegas** [comment]
We could add it but we need to use flash memory. 
It was on Wavelet. 
https://eprint.iacr.org/2021/1432

**Comment by mkannwischer** [comment]
Thanks for the pointer, @gbanegas! We'll cite it in the report. 
pqm4 does not support putting keys in flash memory right now. Also the [NUCLEO-L4R5ZI board](https://www.st.com/en/evaluation-tools/nucleo-l4r5zi.html) only has 2 MiB of flash, so that would not work either.
