### ISSUE TITLE
Integrate Classic McEliece [Round2]

### ISSUE THREAD

**Issue by mkannwischer** [mupq/pqm4#56]
if possible - otherwise document why not.

**Comment by Ko-** [comment]
Public key sizes:

  * `mceliece348864(f)`: 261120 bytes
  * `mceliece460896(f)`: 524160 bytes
  * `mceliece6688128(f)`: 1044992 bytes
  * `mceliece6960119(f)`: 1047319 bytes
  * `mceliece8192128(f)`: 1357824 bytes

This will never fit.
