### ISSUE TITLE
Integrate HQC [Round2]

### ISSUE THREAD

**Issue by mkannwischer** [mupq/pqm4#57]
if possible - otherwise document why not.

**Comment by Ko-** [comment]
This scheme might fit. Unfortunately the implementations depend on the `openssl`, `gmp`, `ntl`, and `gf2x` libraries [[spec](http://pqc-hqc.org/doc/hqc-specification_2019-04-10.pdf)].

**Comment by mkannwischer** [comment]
We are working on integration into PQClean (without libraries). Let's wait for that.

**Comment by mkannwischer** [comment]
https://github.com/PQClean/PQClean/pull/202

**Comment by Ko-** [comment]
HQC has updated [reference implementations](https://pqc-hqc.org/doc/hqc-reference-implementation_2019-08-24.zip), although they still depend on the same libraries. `hqc-128-1` has a peak memory consumption of 198.4 KiB on my laptop, which is not going to fit on our platform. I have not yet checked the optimized implementations.

**Comment by Ko-** [comment]
Apparently, [optimized](https://pqc-hqc.org/doc/hqc-optimized-implementation_2019-08-24.zip) implies AVX2 here, so that's not very useful to `pqm4`.
