### ISSUE TITLE
Integrate LEDAcrypt [Round2]

### ISSUE THREAD

**Issue by mkannwischer** [mupq/pqm4#59]
if possible - otherwise document why not.

**Comment by mkannwischer** [comment]
@leonbotros is working on this.

**Comment by mkannwischer** [comment]
@leonbotros finished the integration into PQClean (for now non-constant time -- to be fixed soon): https://github.com/PQClean/PQClean/pull/186 

Unfortunately, these implementations consume way too much stack space for our board:
- ledakemlt12: 853 KiB
- ledakemlt32: 1533 KiB
- ledakemlt52: 2523 KiB

I think @leonbotros is working on making it fit into less RAM, but for now, there is no fitting implementation.

**Comment by leonbotros** [comment]
Yes, I'm looking into this
