### ISSUE TITLE
Integrate NTS-KEM [Round2]

### ISSUE THREAD

**Issue by mkannwischer** [mupq/pqm4#60]
if possible - otherwise document why not.

**Comment by Ko-** [comment]
Why not: NTS-KEM(12,64), NTS-KEM(13,80), and NTS-KEM(13,136) have public key sizes of 319488, 929760, and 1419704 bytes, respectively [[spec](https://drive.google.com/file/d/1qPsXhK_oXJ88M1ec6pRbvvRKaCMQZfsc/view)]. No way that's going to fit.

**Comment by mkannwischer** [comment]
Thanks
