### ISSUE TITLE
Integrate ROLLO [Round2]

### ISSUE THREAD

**Issue by mkannwischer** [mupq/pqm4#61]
if possible - otherwise document why not.

**Comment by Ko-** [comment]
This scheme might fit. Unfortunately the implementations depend on the `openssl`, `gmp`, and `ntl` libraries.

**Comment by mkannwischer** [comment]
We are working on integration into PQClean (without libraries). Let's wait for that.

**Comment by Ko-** [comment]
ROLLO has updated [reference](https://pqc-rollo.org/doc/rollo-reference-implementation_2019-08-24.zip) and [optimized](https://pqc-rollo.org/doc/rollo-optimized-implementation_2019-08-24.zip) implementations, where dependencies on external libraries appear to be removed. I briefly tried the reference implementation of `ROLLO-I-128` and its peak memory consumption is 17.38 KiB. For the largest parameter set, `ROLLO-III-256`, it is only 44.90 KiB, so it looks like we have another scheme to add!
