### ISSUE TITLE
Integrate RQC [Round2]

### ISSUE THREAD

**Issue by mkannwischer** [mupq/pqm4#63]
if possible - otherwise document why not.

**Comment by Ko-** [comment]
This scheme might fit. Unfortunately the implementations depend on the `openssl`, `gmp`, `ntl`, and `gf2x` libraries [[spec](http://pqc-rqc.org/doc/rqc-specification_2019-04-10.pdf)].

**Comment by mkannwischer** [comment]
We are working on integration into PQClean (without libraries). Let's wait for that.

**Comment by Ko-** [comment]
RQC has updated [reference](https://pqc-rqc.org/doc/rqc-reference-implementation_2019-08-24.zip) and [optimized](https://pqc-rqc.org/doc/rqc-optimized-implementation_2019-08-24.zip) implementations. They removed all dependencies on external libraries. I briefly tested the reference implementation of `rqc128` on my laptop, and it only has a peak memory consumption of 30.56 KiB, so it looks like we have a new scheme to add!
