### ISSUE TITLE
Integrate Rainbow [Round2]

### ISSUE THREAD

**Issue by mkannwischer** [mupq/pqm4#70]
if possible - otherwise document why not.

**Comment by Ko-** [comment]
The public key sizes of normal Rainbow parameter sets Ia, IIIc, and Vc are 149 kB, 710.6 kB, and 1705.5 kB respectively. That will never fit.

For compressed Rainbow, the public key sizes are 58.1 kB, 206.7 kB, and 491.9 kB. Only the first one might fit, but that has a private key of 93 kB. Assuming that both of them have to be in memory at some point, this will never fit.

**Comment by mkannwischer** [comment]
Thanks.
